<?php
header('Content-Type: application/json');
http_response_code(200);
$people=[
["id"=>"1",
"name"=>"david",
"phone"=>"1234",
"address"=>"direccion1",
"email"=>"correoqgmail.com"
],
["id"=>"2",
"name"=>"juan",
"phone"=>"1234",
"address"=>"direccion1",
"email"=>"correoqgmail.com"
],
["id"=>"3",
"name"=>"pdro",
"phone"=>"1234",
"address"=>"direccion1",
"email"=>"correoqgmail.com"
],
["id"=>"4",
"name"=>"carmelo",
"phone"=>"1234",
"address"=>"direccion1",
"email"=>"correoqgmail.com"
],
["id"=>"5",
"name"=>"ipe",
"phone"=>"1234",
"address"=>"direccion1",
"email"=>"correoqgmail.com"
],
["id"=>"6",
"name"=>"clon",
"phone"=>"1234",
"address"=>"direccion1",
"email"=>"correoqgmail.com"
],
["id"=>"7",
"name"=>"coco",
"phone"=>"1234",
"address"=>"direccion1",
"email"=>"correoqgmail.com"
],
["id"=>"8",
"name"=>"carmen",
"phone"=>"1234",
"address"=>"direccion1",
"email"=>"correoqgmail.com"
],
["id"=>"9",
"name"=>"carmelita",
"phone"=>"1234",
"address"=>"direccion1",
"email"=>"correoqgmail.com"
],
["id"=>"10",
"name"=>"ipe",
"phone"=>"1234",
"address"=>"direccion1",
"email"=>"correoqgmail.com"
]
];
echo json_encode($people);
?>